name: Create Pull Request

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Commit message
        branch: new-branch-name  # Change this to the branch name you want to create
        title: Pull Request Title
        body: Pull Request Description
